
services:
  backend:
     container_name: backend
     build:
       context: ./backend
       dockerfile: Dockerfile.dev
    # env_file: 
    #  - .env   
     volumes:
        - ./backend:/app
     restart: always
     ports:
       - 3333:3333    
     environment:
        - NODE_ENV=production
        - DATABASE_URL=postgresql://postgres:postgres@db-postgres:5432/generator?schema=public
        - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET} 
        - BETTER_AUTH_URL=${BETTER_AUTH_URL}
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}  
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} 
        - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID} 
        - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
        - OPENAI_API_KEY=${OPENAI_API_KEY} 
     networks:
       - sentences_app_network   
     depends_on:
       - db-postgres
           
  frontend: 
    container_name: frontend
    build:
     context: ./frontend
     dockerfile: Dockerfile.dev 
    env_file: 
      - .env   
    volumes:
      - ./frontend:/app
    restart: always
    ports:
       - 3000:3000
    networks:
       - sentences_app_network   
    depends_on:
       - backend


  db-postgres:
    container_name: db-postgres
    image: postgres:16.10-alpine3.21
    restart: always
    environment:
        ALLOW_EMPTY_PASSWORD: yes
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: generator 
    volumes:
      - db-app:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - sentences_app_network
      
volumes:
  db-app:

networks:
  sentences_app_network:
     driver: bridge